name: super_equipes
description: "Aplicativo para sorteio de times."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  sizer: ^3.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

#Gera splashScreen da aplicação
flutter_native_splash:
  color: "#f7fbf2"
  image: assets/splash/splash_screen.png
  color_dark: "#101410"
  android: true
  ios: true

  android_12:
    color: "#f7fbf2"
    image: assets/splash/splash_screen_v12.png
    color_dark: "#101410"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/google_fonts/Poppins/Poppins-Black.ttf
      - asset: assets/google_fonts/Poppins/Poppins-BlackItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Bold.ttf
      - asset: assets/google_fonts/Poppins/Poppins-BoldItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraBold.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraBoldItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraLight.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraLightItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Italic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Light.ttf
      - asset: assets/google_fonts/Poppins/Poppins-LightItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Medium.ttf
      - asset: assets/google_fonts/Poppins/Poppins-MediumItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Regular.ttf
      - asset: assets/google_fonts/Poppins/Poppins-SemiBold.ttf
      - asset: assets/google_fonts/Poppins/Poppins-SemiBoldItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Thin.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ThinItalic.ttf

  - family: Roboto
    fonts:
      - asset: assets/google_fonts/Roboto/Roboto-Black.ttf
      - asset: assets/google_fonts/Roboto/Roboto-BlackItalic.ttf
      - asset: assets/google_fonts/Roboto/Roboto-Bold.ttf
      - asset: assets/google_fonts/Roboto/Roboto-BoldItalic.ttf
      - asset: assets/google_fonts/Roboto/Roboto-Italic.ttf
      - asset: assets/google_fonts/Roboto/Roboto-Light.ttf
      - asset: assets/google_fonts/Roboto/Roboto-LightItalic.ttf
      - asset: assets/google_fonts/Roboto/Roboto-Medium.ttf
      - asset: assets/google_fonts/Roboto/Roboto-MediumItalic.ttf
      - asset: assets/google_fonts/Roboto/Roboto-Regular.ttf
      - asset: assets/google_fonts/Roboto/Roboto-Thin.ttf
      - asset: assets/google_fonts/Roboto/Roboto-ThinItalic.ttf