import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:sizer/sizer.dart';
import 'package:super_equipes/core/theme/ui_helpers/ui_helpers.dart';

TextStyle get titleStyle => GoogleFonts.poppins(fontSize: 20.s2, fontWeight: FontWeight.w500, decoration: TextDecoration.none);
TextStyle get subtitleStyle => GoogleFonts.roboto(fontSize: 14.s2, fontWeight: FontWeight.normal, decoration: TextDecoration.none);
TextStyle get bodyStyle => GoogleFonts.roboto(fontSize: 12.s4, fontWeight: FontWeight.w600, decoration: TextDecoration.none);
TextStyle get textFieldStyle => GoogleFonts.roboto(fontSize: 14.s2, fontWeight: FontWeight.w400, decoration: TextDecoration.none);
TextStyle get fabStyle => GoogleFonts.roboto(fontSize: 14.s2, fontWeight: FontWeight.w500, decoration: TextDecoration.none);
TextStyle get inkTitleStyle => GoogleFonts.roboto(fontSize: 18.s2, fontWeight: FontWeight.w700, decoration: TextDecoration.none);
TextStyle get inkSubTitleStyle => GoogleFonts.poppins(fontSize: 12.s2, fontWeight: FontWeight.w600, decoration: TextDecoration.none);
TextStyle get timeTitleStyle => GoogleFonts.roboto(fontSize: 18.s2, fontWeight: FontWeight.w400, decoration: TextDecoration.none);
TextStyle get nomeJogadorStyle => GoogleFonts.roboto(fontSize: 13.s2, fontWeight: FontWeight.bold, color: Get.theme.colorScheme.customColor, decoration: TextDecoration.none);
TextStyle get estatisticaStyle => GoogleFonts.roboto(fontSize: 11.7.s2, fontWeight: FontWeight.bold, color: Get.theme.colorScheme.customColor, decoration: TextDecoration.none);
TextStyle get nomeJogadorStyleMinor => GoogleFonts.roboto(fontSize: 11.s4, fontWeight: FontWeight.bold, color: Get.theme.colorScheme.customColor, decoration: TextDecoration.none);
TextStyle get estatisticaStyleMinor => GoogleFonts.roboto(fontSize: isMobile ? 9.5.s : Device.orientation == Orientation.portrait ? 9.2.s4 : 8.4.s4, fontWeight: FontWeight.bold, color: Get.theme.colorScheme.customColor, decoration: TextDecoration.none);
TextStyle get hintStyle => GoogleFonts.roboto(fontSize: 14.s1, fontWeight: FontWeight.w300, color: Get.theme.colorScheme.onSurfaceVariant, decoration: TextDecoration.none);
TextStyle get errorStyle => GoogleFonts.roboto(fontSize: 11.s1, fontWeight: FontWeight.normal, color: Get.theme.colorScheme.error, decoration: TextDecoration.none);
TextStyle get dialogTitleStyle => GoogleFonts.poppins(fontSize: 15.s2, fontWeight: FontWeight.w500, decoration: TextDecoration.none);
TextStyle get dialogContentStyle => GoogleFonts.roboto(fontSize: 12.s2, fontWeight: FontWeight.normal, decoration: TextDecoration.none);
TextStyle get dialogConfirmStyle => GoogleFonts.roboto(fontSize: 12.s2, fontWeight: FontWeight.w600, decoration: TextDecoration.none);
TextStyle get dialogCancelStyle => GoogleFonts.roboto( fontSize: 12.s2, fontWeight: FontWeight.w600, color: Get.theme.colorScheme.error, decoration: TextDecoration.none);